#pragma once
#include <templates/macro/abbrev/eb.hpp>
#include <templates/macro/abbrev/endl.hpp>
#include <templates/macro/abbrev/ext.hpp>
#include <templates/macro/abbrev/greater.hpp>
#include <templates/macro/abbrev/ldouble.hpp>
#include <templates/macro/abbrev/lint.hpp>
#include <templates/macro/abbrev/ll.hpp>
#include <templates/macro/abbrev/mp.hpp>
#include <templates/macro/abbrev/pb.hpp>
#include <templates/macro/abbrev/space.hpp>
#include <templates/macro/abbrev/ull.hpp>
