#pragma once
#include <fastio/base.hpp>
#include <fastio/char/read.hpp>
#include <fastio/char/write.hpp>
#include <fastio/double/read.hpp>
#include <fastio/double/write.hpp>
#include <fastio/int128/read.hpp>
#include <fastio/int128/write.hpp>
#include <fastio/modint/read.hpp>
#include <fastio/modint/write.hpp>
#include <fastio/pair/read.hpp>
#include <fastio/point/read.hpp>
#include <fastio/signed/read.hpp>
#include <fastio/signed/write.hpp>
#include <fastio/string/read.hpp>
#include <fastio/string/write.hpp>
#include <fastio/unsigned/read.hpp>
#include <fastio/unsigned/write.hpp>
#include <fastio/vector/read.hpp>
#include <fastio/vector/write.hpp>
