#pragma once
#include <templates/chmin_max.hpp>
#include <templates/graph.hpp>
#include <templates/grid.hpp>
#include <templates/macro/all.hpp>
#include <templates/pair.hpp>
#include <templates/ranges.hpp>
#include <templates/rep.hpp>
#include <templates/unique.hpp>
#include <templates/vector.hpp>
