#pragma once
#include <templates/macro/segtree/RAMQ.hpp>
#include <templates/macro/segtree/RASQ.hpp>
#include <templates/macro/segtree/RAmQ.hpp>
#include <templates/macro/segtree/RMQ.hpp>
#include <templates/macro/segtree/RSQ.hpp>
#include <templates/macro/segtree/RUMQ.hpp>
#include <templates/macro/segtree/RUSQ.hpp>
#include <templates/macro/segtree/RUmQ.hpp>
#include <templates/macro/segtree/RmQ.hpp>
